#!/bin/bash
echo "=== EspressoBot Server Restart Required ==="
echo ""
echo "Changes made:"
echo "1. Added Shopify Orders Agent for order analytics"
echo "2. Fixed gpt-4.1-mini model errors - will retry with gpt-4o-mini ONLY on failure"
echo ""
echo "To restart:"
echo "1. Press Ctrl+C in the terminal running 'pnpm dev'"
echo "2. Run 'pnpm dev' again"
echo ""
echo "After restart, the Shopify Orders Agent will be available with these capabilities:"
echo "- shopify_orders_agent: Direct access to order analytics"
echo "- analytics_daily_sales: Quick daily sales summaries"
echo "- analytics_order_summary: Detailed order analytics with product breakdowns"
echo "- analytics_revenue_report: Comprehensive revenue reports"
echo ""
echo "The agent will automatically route queries about:"
echo "- Daily sales"
echo "- Order analytics"
echo "- Revenue reports"
echo "- Sales summaries"
echo ""
echo "To test after restart, ask EB1:"
echo "- 'Get today's sales summary'"
echo "- 'Show order analytics for the last week'"
echo "- 'Generate a revenue report for this month'"