"""add embedding cache tables for persistent storage

Revision ID: 5a2d1602c6c9
Revises: 81dd0505934c
Create Date: 2025-05-26 09:43:28.276405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a2d1602c6c9'
down_revision = '81dd0505934c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embedding_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text_hash', sa.String(length=64), nullable=False),
    sa.Column('text_content', sa.Text(), nullable=False),
    sa.Column('embedding_data', sa.LargeBinary(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_accessed', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('embedding_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_embedding_cache_text_hash'), ['text_hash'], unique=True)

    op.create_table('user_memory_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('memory_key', sa.String(length=255), nullable=False),
    sa.Column('embedding_cache_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['embedding_cache_id'], ['embedding_cache.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'memory_key', name='unique_user_memory_embedding')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_memory_embeddings')
    with op.batch_alter_table('embedding_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_embedding_cache_text_hash'))

    op.drop_table('embedding_cache')
    # ### end Alembic commands ###
